import { ChevronLeft, LoaderCircle } from 'lucide-react';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { useLocation, useNavigate } from 'react-router';
import { createCategoriesApi, type Category } from '@/api/categories';
import { createClient } from '@/api/client';
import { createExpensesApi } from '@/api/expenses';
import { createReceiptsApi } from '@/api/receipts';
import { COLLAPSED_KEYS, ExpenseForm, validateExpense, type ExpenseFields } from '@/components/expense-form';
import { ItemsEditor, type ItemFields, validateItems } from '@/components/items-editor';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { confirmReceiptPath } from '@/client-routes';
import { describeFailure } from '@/api/messages';
import { todayInMalaysia } from '@/lib/money';
import { useSession } from '@/session/context';

const MAX_BYTES=10*1024*1024; const TYPES=new Set(['image/jpeg','image/png','image/webp','image/heic','image/heif']);
const empty={categoryId:'',total:'',purchasedOn:todayInMalaysia(),merchantName:'',purchasedAtTime:'',merchantTaxId:'',receiptNumber:'',subtotal:'',tax:'',rounding:'',currency:'',paymentMethod:'',note:''};
const transport=(url:string,init:RequestInit)=>fetch(url,init);
export function AddExpenseScreen() { const navigate=useNavigate(), location=useLocation(), {session}=useSession(); const [request]=useState(()=>createClient('',transport)), [categoriesApi]=useState(()=>createCategoriesApi(request)), [expensesApi]=useState(()=>createExpensesApi(request)), [receiptsApi]=useState(()=>createReceiptsApi(request)); const [fields,setFields]=useState<ExpenseFields>(empty),[categories,setCategories]=useState<Category[]>([]),[errors,setErrors]=useState<Record<string,string>>({}),[items,setItems]=useState<ItemFields[]>([]),[expanded,setExpanded]=useState(false),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[notice,setNotice]=useState<string>(),[retry,setRetry]=useState<File>(); const camera=useRef<HTMLInputElement>(null), picker=useRef<HTMLInputElement>(null);
  useEffect(()=>{void session.authorized(token=>categoriesApi.list(token)).then(result=>{if(result.kind==='ok')setCategories(result.body);else if(!(result.kind==='error'&&result.status===401))setNotice(describeFailure(result));});},[categoriesApi,session]);
  const change=(name:keyof ExpenseFields,value:string)=>{setFields(current=>({...current,[name]:value}));setErrors(current=>{const next={...current};delete next[name];return next;});};
  const upload=async(file:File)=>{setNotice(undefined);if(file.size>MAX_BYTES){setNotice('That photo is larger than 10 MB.');return;}if(file.type!==''&&!TYPES.has(file.type.toLowerCase())){setNotice('Must be a JPEG, PNG, WebP or HEIC image.');return;}setUploading(true);const result=await session.authorized(token=>receiptsApi.upload(token,file));setUploading(false);if(result.kind==='ok'){navigate(confirmReceiptPath(result.body.id));return;}if(result.kind==='offline'){setRetry(file);setNotice('Could not reach the server. Check your connection.');}else if(!(result.kind==='error'&&result.status===401))setNotice(result.kind==='error'&&result.status===429?(result.retryAfterSeconds===undefined?'Too many uploads. Please wait a moment and try again.':`Too many uploads. Try again in ${result.retryAfterSeconds} ${result.retryAfterSeconds===1?'second':'seconds'}.`):describeFailure(result));};
  async function save(event:FormEvent){event.preventDefault();const checked=validateExpense(fields), itemChecked=validateItems(items);setErrors({...checked.errors,...itemChecked.errors});if(!checked.values||!itemChecked.values)return;const values=checked.values;setSaving(true);const result=await session.authorized(token=>expensesApi.create(token,{...values,categoryId:values.categoryId!,totalCents:values.totalCents!,purchasedOn:values.purchasedOn!,items:itemChecked.values}));if(result.kind==='ok'){const category=categories.find(category=>category.id===fields.categoryId)?.name??'category';navigate('/',{replace:true,state:{notice:`Filed ${fields.merchantName||'expense'}, RM ${Number(fields.total).toFixed(2)} under ${category}.`}});return;}setSaving(false);if(result.kind==='error'&&result.status===400&&result.fields){setErrors(result.fields);if(Object.keys(result.fields).some(key=>COLLAPSED_KEYS.has(key)))setExpanded(true);}else if(result.kind==='error'&&result.status===422&&result.message==='Category not found'){const next=await session.authorized(token=>categoriesApi.list(token));if(next.kind==='ok')setCategories(next.body);setErrors({categoryId:'That category is no longer available. Choose another.'});}else if(!(result.kind==='error'&&result.status===401))setErrors({form:describeFailure(result)});}
  return <main className="mx-auto min-h-dvh w-full max-w-xl px-4 pb-28"><header className="flex items-center gap-2 py-3"><Button type="button" variant="ghost" size="icon" className="size-11" aria-label="Back" onClick={()=>navigate(location.state?.from??-1)}><ChevronLeft/></Button><h1 className="font-heading text-lg font-semibold">Add expense</h1></header>{notice&&<Alert variant="destructive" role="alert"><AlertDescription>{notice}</AlertDescription></Alert>}{errors.form&&<Alert variant="destructive" role="alert"><AlertDescription>{errors.form}</AlertDescription></Alert>}<div className="mb-4 flex gap-2"><Button type="button" onClick={()=>camera.current?.click()}>Take photo</Button><Button type="button" variant="outline" onClick={()=>picker.current?.click()}>Upload photo</Button><input ref={camera} aria-label="Take photo" className="sr-only" type="file" accept="image/*" capture="environment" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);}}/><input ref={picker} aria-label="Upload photo" className="sr-only" type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);}}/></div>{uploading&&<p className="mb-4 flex gap-2"><LoaderCircle className="animate-spin"/>Reading your receipt…</p>}{retry&&<div className="mb-4 flex gap-2"><Button onClick={()=>void upload(retry)}>Retry</Button><Button variant="outline" onClick={()=>{setRetry(undefined);setNotice(undefined);}}>Discard</Button></div>}<ExpenseForm fields={fields} errors={errors} categories={categories} expanded={expanded} onToggleDetails={()=>setExpanded(open=>!open)} onChange={change} onSubmit={save} submitLabel="Save expense" saving={saving} canSubmit={Boolean(fields.categoryId)}/><ItemsEditor items={items} setItems={setItems} errors={errors} targetCents={undefined}/></main>; }
