import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { Database } from '../db.js';
import { authenticatedUserId, requireAuth } from '../auth/guard.js';
import { findLiveCategoryById } from '../categories/categories.js';
import { fieldErrors } from '../validation.js';

const body = z.object({ detectedName: z.string().trim().min(1), merchantName: z.string().trim().min(1), categoryId: z.string().uuid() });
const id = z.string().uuid();
export function normalizeMerchant(value: string): string { return value.normalize('NFKC').toLocaleLowerCase().replace(/[\s\p{P}]+/gu, ''); }
const row = `SELECT r.id, r.detected_name AS "detectedName", r.merchant_name AS "merchantName", r.category_id AS "categoryId", c.name AS "categoryName", c.deleted_at IS NULL AS "categoryActive", r.created_at AS "createdAt", r.updated_at AS "updatedAt" FROM merchant_corrections r JOIN categories c ON c.id = r.category_id`;
async function valid(db: Database, user: string, category: string) { return Boolean(await findLiveCategoryById(db.pool, user, category)); }
export function registerMerchantCorrectionRoutes(app: FastifyInstance, { database }: { database: Database }) {
  app.addHook('preHandler', requireAuth);
  app.get('/merchant-corrections', async (request, reply) => reply.send((await database.pool.query(`${row} WHERE r.user_id = $1 ORDER BY r.detected_name`, [authenticatedUserId(request)])).rows));
  app.post('/merchant-corrections', async (request, reply) => { const p = body.safeParse(request.body); if (!p.success) return reply.code(400).send({ error:'Validation failed', fields:fieldErrors(p.error) }); const user=authenticatedUserId(request); if (!await valid(database,user,p.data.categoryId)) return reply.code(422).send({error:'Category not found'}); try { const q=await database.pool.query(`WITH changed AS (INSERT INTO merchant_corrections (user_id,detected_name,normalized_name,merchant_name,category_id) VALUES ($1,$2,$3,$4,$5) RETURNING id) ${row} JOIN changed ON changed.id = r.id`,[user,p.data.detectedName,normalizeMerchant(p.data.detectedName),p.data.merchantName,p.data.categoryId]); return reply.code(201).send(q.rows[0]); } catch (e) { if ((e as {code?:string}).code==='23505') return reply.code(409).send({error:'A correction for that detected merchant already exists'}); throw e; } });
  app.patch('/merchant-corrections/:id', async (request, reply) => { const key=id.safeParse((request.params as {id?:unknown}).id); const p=body.safeParse(request.body); if (!key.success) return reply.code(404).send({error:'Merchant correction not found'}); if (!p.success) return reply.code(400).send({error:'Validation failed',fields:fieldErrors(p.error)}); const user=authenticatedUserId(request); if (!await valid(database,user,p.data.categoryId)) return reply.code(422).send({error:'Category not found'}); try { const q=await database.pool.query(`WITH changed AS (UPDATE merchant_corrections SET detected_name=$3,normalized_name=$4,merchant_name=$5,category_id=$6,updated_at=now() WHERE id=$1 AND user_id=$2 RETURNING id) ${row} JOIN changed ON changed.id = r.id`,[key.data,user,p.data.detectedName,normalizeMerchant(p.data.detectedName),p.data.merchantName,p.data.categoryId]); if(!q.rows[0]) return reply.code(404).send({error:'Merchant correction not found'}); return reply.send(q.rows[0]); } catch(e) {if((e as {code?:string}).code==='23505')return reply.code(409).send({error:'A correction for that detected merchant already exists'});throw e;} });
  app.delete('/merchant-corrections/:id', async (request, reply) => { const key=id.safeParse((request.params as {id?:unknown}).id); if(!key.success)return reply.code(404).send({error:'Merchant correction not found'}); const q=await database.pool.query('DELETE FROM merchant_corrections WHERE id=$1 AND user_id=$2 RETURNING id',[key.data,authenticatedUserId(request)]); return q.rows[0]?reply.code(204).send():reply.code(404).send({error:'Merchant correction not found'}); });
}
